name: Manual Staging Deploy
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Confirm deployment to staging"
        required: true
        default: "yes"
jobs:
  build-and-deploy:
    name: Deploy to staging
    if: ${{ github.event.inputs.confirm == 'yes' }}
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      ENVIRONMENT: staging
    secrets: inherit
